server:
  port: 8080

spring:
  datasource:
    druid:
      # jdbc
      url: jdbc:mysql://192.168.1.8:3306/runmin?useUnicode=true&characterEncoding=utf8
      username: root
      password: s123456
      driver-class-name: com.mysql.jdbc.Driver
      # 连接池
      # 初始化连接数
      initial-size: 1
      # 最大连接数量
      max-active: 3000
      # 最小空闲数量
      min-idle: 5
      # 最大连接等待超时时长
      max-wait: 70000
      # 检测配置
      validation-query: select 1
      validation-query-timeout: 20
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

redis:
  host: 192.168.1.3
  password: s123456
  jedis:
    pool:
      max-active: 100
      max-idle: 10
      min-idle: 1

mvc:
  # 404 抛出错误
  throw-exception-if-no-handler-found: true

mybatis:
  # 实体对象所在的包
  typeAliasesPackage: com.lanceyi.small.model
  # mapper所在的位置
  mapper-locations: classpath:mappers/*.xml
  #驼峰映射
  configuration:
    mapUnderscoreToCamelCase: true
