package com.lanceyi.small.model;

import java.io.Serializable;

public class Admin implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_id
     *
     * @mbggenerated
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.real_name
     *
     * @mbggenerated
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.login_name
     *
     * @mbggenerated
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.login_pwd
     *
     * @mbggenerated
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_sex
     *
     * @mbggenerated
     */
    private Byte adminSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_phone
     *
     * @mbggenerated
     */
    private String adminPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_activation
     *
     * @mbggenerated
     */
    private Byte adminActivation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_effective
     *
     * @mbggenerated
     */
    private Byte adminEffective;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.last_ip
     *
     * @mbggenerated
     */
    private String lastIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.last_time
     *
     * @mbggenerated
     */
    private Integer lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.admin_type
     *
     * @mbggenerated
     */
    private Integer adminType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.creator
     *
     * @mbggenerated
     */
    private Integer creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.root_id
     *
     * @mbggenerated
     */
    private String rootId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.note
     *
     * @mbggenerated
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table admin
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_id
     *
     * @return the value of admin.admin_id
     *
     * @mbggenerated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_id
     *
     * @param adminId the value for admin.admin_id
     *
     * @mbggenerated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.real_name
     *
     * @return the value of admin.real_name
     *
     * @mbggenerated
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.real_name
     *
     * @param realName the value for admin.real_name
     *
     * @mbggenerated
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.login_name
     *
     * @return the value of admin.login_name
     *
     * @mbggenerated
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.login_name
     *
     * @param loginName the value for admin.login_name
     *
     * @mbggenerated
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.login_pwd
     *
     * @return the value of admin.login_pwd
     *
     * @mbggenerated
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.login_pwd
     *
     * @param loginPwd the value for admin.login_pwd
     *
     * @mbggenerated
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_sex
     *
     * @return the value of admin.admin_sex
     *
     * @mbggenerated
     */
    public Byte getAdminSex() {
        return adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_sex
     *
     * @param adminSex the value for admin.admin_sex
     *
     * @mbggenerated
     */
    public void setAdminSex(Byte adminSex) {
        this.adminSex = adminSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_phone
     *
     * @return the value of admin.admin_phone
     *
     * @mbggenerated
     */
    public String getAdminPhone() {
        return adminPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_phone
     *
     * @param adminPhone the value for admin.admin_phone
     *
     * @mbggenerated
     */
    public void setAdminPhone(String adminPhone) {
        this.adminPhone = adminPhone == null ? null : adminPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_activation
     *
     * @return the value of admin.admin_activation
     *
     * @mbggenerated
     */
    public Byte getAdminActivation() {
        return adminActivation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_activation
     *
     * @param adminActivation the value for admin.admin_activation
     *
     * @mbggenerated
     */
    public void setAdminActivation(Byte adminActivation) {
        this.adminActivation = adminActivation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_effective
     *
     * @return the value of admin.admin_effective
     *
     * @mbggenerated
     */
    public Byte getAdminEffective() {
        return adminEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_effective
     *
     * @param adminEffective the value for admin.admin_effective
     *
     * @mbggenerated
     */
    public void setAdminEffective(Byte adminEffective) {
        this.adminEffective = adminEffective;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.create_time
     *
     * @return the value of admin.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.create_time
     *
     * @param createTime the value for admin.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.last_ip
     *
     * @return the value of admin.last_ip
     *
     * @mbggenerated
     */
    public String getLastIp() {
        return lastIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.last_ip
     *
     * @param lastIp the value for admin.last_ip
     *
     * @mbggenerated
     */
    public void setLastIp(String lastIp) {
        this.lastIp = lastIp == null ? null : lastIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.last_time
     *
     * @return the value of admin.last_time
     *
     * @mbggenerated
     */
    public Integer getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.last_time
     *
     * @param lastTime the value for admin.last_time
     *
     * @mbggenerated
     */
    public void setLastTime(Integer lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.admin_type
     *
     * @return the value of admin.admin_type
     *
     * @mbggenerated
     */
    public Integer getAdminType() {
        return adminType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.admin_type
     *
     * @param adminType the value for admin.admin_type
     *
     * @mbggenerated
     */
    public void setAdminType(Integer adminType) {
        this.adminType = adminType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.creator
     *
     * @return the value of admin.creator
     *
     * @mbggenerated
     */
    public Integer getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.creator
     *
     * @param creator the value for admin.creator
     *
     * @mbggenerated
     */
    public void setCreator(Integer creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.root_id
     *
     * @return the value of admin.root_id
     *
     * @mbggenerated
     */
    public String getRootId() {
        return rootId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.root_id
     *
     * @param rootId the value for admin.root_id
     *
     * @mbggenerated
     */
    public void setRootId(String rootId) {
        this.rootId = rootId == null ? null : rootId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.note
     *
     * @return the value of admin.note
     *
     * @mbggenerated
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.note
     *
     * @param note the value for admin.note
     *
     * @mbggenerated
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", adminId=").append(adminId);
        sb.append(", realName=").append(realName);
        sb.append(", loginName=").append(loginName);
        sb.append(", loginPwd=").append(loginPwd);
        sb.append(", adminSex=").append(adminSex);
        sb.append(", adminPhone=").append(adminPhone);
        sb.append(", adminActivation=").append(adminActivation);
        sb.append(", adminEffective=").append(adminEffective);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastIp=").append(lastIp);
        sb.append(", lastTime=").append(lastTime);
        sb.append(", adminType=").append(adminType);
        sb.append(", creator=").append(creator);
        sb.append(", rootId=").append(rootId);
        sb.append(", note=").append(note);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}